# Implement an algorithm to determine if a string has all unique characters.
# What if you can't use additional data structures?
import sys
from collections import defaultdict
import LinkedList

class HashTable:
    keys = list()
    vals = list()

    def __init__(self, size) -> None:
        for i in range(size):
            self.vals.append(LinkedList()) # empty linkedlists
        self.size = size

    def add(self, key, val):
        if key not in self.keys: # Should we care about duplicate keys?
            self.keys.append(key)

        idx = hash(key) % self.size
        self.vals[idx].add(val) # add value to linked list at the index generated by the hash (mod size)

    def get(self, key, val):
        idx = hash(key) % self.size
        return self.vals[idx].get(val) # if None value is not present?

        
        
def isUnique(useDataStructures: bool, string: str):
    if useDataStructures:
        alphabet = defaultdict(int)
        for s in string:
            if alphabet[s] > 0: # already found an instance, not unique
                return False
            alphabet[s] += 1
        return True
    else: #todo make own hash table

        pass

def main():
    # argv = [ isUnique.py, useDataStrucutures (T/F), Word (String) ]

    pass

if __name__ == "__main__":
    main()